version: '3.8'

services:
  web:
    build: .
    container_name: django-todo-app
    command: gunicorn todoApp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    restart: always
